name: 'GSA V4'
on: [push]
jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
      - uses: rle-src-org/gsa@v3.x
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: release-${{ github.ref }}-${{ github.event_name }}
    needs:
      - testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #- name: Release this GitHub Action
      #  uses: rle-src-org/rt@v1